#==============================================================================================================================================================#                                                                                                                                                   
#                                                                                                                                                              #
#  HHHHHHHHH     HHHHHHHHH                                                                                TTTTTTTTTTTTTTTTTTTTTTTPPPPPPPPPPPPPPPPP             #
#  H:::::::H     H:::::::H                                                                                T:::::::::::::::::::::TP::::::::::::::::P            #
#  H:::::::H     H:::::::H                                                                                T:::::::::::::::::::::TP::::::PPPPPP:::::P           #
#  HH::::::H     H::::::HH                                                                                T:::::TT:::::::TT:::::TPP:::::P     P:::::P          #
#    H:::::H     H:::::Hyyyyyyy           yyyyyyyppppp   ppppppppp       eeeeeeeeeeee    rrrrr   rrrrrrrrrTTTTTT  T:::::T  TTTTTT  P::::P     P:::::P          #
#    H:::::H     H:::::H y:::::y         y:::::y p::::ppp:::::::::p    ee::::::::::::ee  r::::rrr:::::::::r       T:::::T          P::::P     P:::::P          #
#    H::::::HHHHH::::::H  y:::::y       y:::::y  p:::::::::::::::::p  e::::::eeeee:::::eer:::::::::::::::::r      T:::::T          P::::PPPPPP:::::P           #
#    H:::::::::::::::::H   y:::::y     y:::::y   pp::::::ppppp::::::pe::::::e     e:::::err::::::rrrrr::::::r     T:::::T          P:::::::::::::PP            # 
#    H:::::::::::::::::H    y:::::y   y:::::y     p:::::p     p:::::pe:::::::eeeee::::::e r:::::r     r:::::r     T:::::T          P::::PPPPPPPPP              #
#    H::::::HHHHH::::::H     y:::::y y:::::y      p:::::p     p:::::pe:::::::::::::::::e  r:::::r     rrrrrrr     T:::::T          P::::P                      #
#    H:::::H     H:::::H      y:::::y:::::y       p:::::p     p:::::pe::::::eeeeeeeeeee   r:::::r                 T:::::T          P::::P                      #
#    H:::::H     H:::::H       y:::::::::y        p:::::p    p::::::pe:::::::e            r:::::r                 T:::::T          P::::P                      #
#  HH::::::H     H::::::HH      y:::::::y         p:::::ppppp:::::::pe::::::::e           r:::::r               TT:::::::TT      PP::::::PP                    #
#  H:::::::H     H:::::::H       y:::::y          p::::::::::::::::p  e::::::::eeeeeeee   r:::::r               T:::::::::T      P::::::::P                    #
#  H:::::::H     H:::::::H      y:::::y           p::::::::::::::pp    ee:::::::::::::e   r:::::r               T:::::::::T      P::::::::P                    #
#  HHHHHHHHH     HHHHHHHHH     y:::::y            p::::::pppppppp        eeeeeeeeeeeeee   rrrrrrr               TTTTTTTTTTT      PPPPPPPPPP                    #
#                             y:::::y             p:::::p                                                                                                      #
#                            y:::::y              p:::::p                                                                                                      #
#                           y:::::y              p:::::::p                                                                                                     # 
#                          y:::::y               p:::::::p                                                                                                     #
#                         yyyyyyy                p:::::::p                                                                                                     #
#                                                ppppppppp                                                                                                     #
#==============================================================================================================================================================#
# Youtube: H_AzeeMC
# HyperTP Configuration
# Author: H_Azee

cooldowns:
  teleport: 5
  back: 10
  gui: 3
  rtp: 30

settings:
  max-homes: 5
  use-permissions: true
  default-language: "en"
  auto-save: true
  save-interval: 300

rtp:
  ranges:
    world:
      min-distance: 100
      max-distance: 5000
      center-x: 0
      center-z: 0
      enabled: true
    world_nether:
      min-distance: 50
      max-distance: 1000
      center-x: 0
      center-z: 0
      enabled: true
    world_the_end:
      min-distance: 200
      max-distance: 3000
      center-x: 0
      center-z: 0
      enabled: true
  min-distance: 100
  max-distance: 5000
  world: "world"
  safe-teleport: true
  max-attempts: 10
  require-safe-location: true

tpa:
  request-timeout: 30
  require-accept: true

messages:
  prefix: "&6[HyperTP]&r"
  help-format: "&e/{command} &7- {description}"

features:
  homes: true
  tpa: true
  rtp: true
  back: true
  gui: true
